language: node_js
node_js:
  - "12"
cache:
  directories:
    - "node_modules"

services:
  - mongodb

after_success: npm run coverage

deploy:
  provider: pages
  on:
    branch: develop

notifications:
  email: false
